### ISSUE TITLE
zero division error when using ei utility function

### ISSUE THREAD

**Issue by Yoonho-Na** [bayesian-optimization/BayesianOptimization#516] opened 2024-08-20 02:00 UTC
**Describe the bug**
Using `bayesian-optimization==1.4.3` results in `bayes_opt/util.py:169: RuntimeWarning: divide by zero encountered in true_divide
  z = a / std`.

I used utility function like this
`ei = UtilityFunction(kind="ei", xi=1e-1)`

**Screenshots**

<img width="762" alt="스크린샷 2024-08-20 오전 10 58 58" src="https://github.com/user-attachments/assets/496868f9-5453-4a8c-8d55-7a52c00cc4b5">

**Comment by till-m** [comment] 2024-08-20 08:05
Hi @Yoonho-Na,

It looks like the GP predicts a standard deviation of 0, which can happen because of many things. Without more information we can't really tell you what exactly is the cause here.

**Comment by till-m** [comment] 2024-08-24 08:11
I will close this issue for now. Feel free to reopen with more information.

**Closed by till-m** 2024-08-24 08:11 UTC
Labels: bug, enhancement
