### ISSUE TITLE
Potential for ANSI colours to remain active

### ISSUE THREAD

**Issue by d7919** [bayesian-optimization/BayesianOptimization#488] opened 2024-07-04 10:10 UTC
In `_step` of logger, the colour remains active after the line is displayed, i.e. it is not reset.

https://github.com/bayesian-optimization/BayesianOptimization/blob/3a5e56c7d0f96affdebfebc318b02f71f0462be3/bayes_opt/logger.py#L166

If the user's function has any output or if the system displays any output this will inherit the colour of the last output. This can also potentially cause issues if the user kills the job mid-run leaving the colour code active.

Changing this line to 

~~~~python
return "| " + " | ".join([colour + cells[i] + Fore.RESET for i in range(len(cells))]) + " |" 
~~~~

is perhaps a bit "safer"  and has the minor advantage of not colouring the `|` column separators.

On a side note, it would be helpful if the user could:

1. Turn off the colouring (if capturing output the escape codes can enter the log file).
2. Choose the two colours in use -- for me the default Black is unreadable due to the colour of my terminal background.

**Comment by till-m** [comment] 2024-07-05 14:22
Hi @d7919,

regarding the cause for the issue, good catch, this should indeed be fixed. Thanks for providing a PR!

> side note

you raise some good points:
> Choose the two colours in use -- for me the default Black is unreadable due to the colour of my terminal background.

I think it would make sense to replace `Fore.BLACK` with `Fore.RESET` in general. What do you think? This would probably alleviate the issue for most cases and be relatively low effort. However, if you feel strongly about making the `ScreenLogger` more flexible/customizable (turning colours off or using different colours), and are willing submit a PR for this, I will gladly review and merge it :)

**Comment by till-m** [comment] 2024-07-10 06:44
I will close this for now

**Closed by till-m** 2024-07-10 06:44 UTC
