### ISSUE TITLE
Bounds Transformer doesn't work after loading the logs

### ISSUE THREAD

**Issue by pawlissimo** [bayesian-optimization/BayesianOptimization#486] opened 2024-06-25 15:00 UTC
**Bounds Transformer doesn't work after loading the logs**
`bayesian-optimization==1.5.0`

High-level flow:
1. Create `original_logger = JSONLogger(path="./original_logsr.json"), reset=True) 
2. Create `original_bounds_transformer = SequentialDomainReductionTransformer()`
3. Create `original_optimizer = BayesianOptimization(... bounds_transformer=original_bounds_transformer)`
4. Subscribe logger `original_optimizer.subscribe(Events.OPTIMIZATION_STEP, original_logger )` 
5. Run optimization `original_optimizer .maximize(init_points=2, n_iter=10)`
6. Create new `loaded_optimizer` with new `loaded_bounds_transformer` in the same way and  `load_logs(loaded_optimizer, logs=""./original_logsr.json")`.
7. Call `maximize(n_iter=10)` for both optimizers and compare their results + optimizers.
You will see that `loaded_optimizer` has wrong values like its bounds_transformer becomes "broken" or irresponsive.

The main goal of such flow is to have a "checkpoint" and continue optimization later.
**P.S.** I've tried many different options with dumping transformer content using `pickle`, updating it, transforming, etc without any luck
**Note** I carefully read whole documentation and followed most of examples., but was not able to find the proper way.

**To Reproduce**
```python
## core idea described here: https://bayesian-optimization.github.io/BayesianOptimization/domain_reduction.html
import numpy as np
from bayes_opt import BayesianOptimization
from bayes_opt import SequentialDomainReductionTransformer
from bayes_opt.logger import JSONLogger
from bayes_opt.event import Events
from bayes_opt.util import load_logs
import matplotlib.pyplot as plt


pbounds = {'x': (-5, 5), 'y': (-5, 5)}
def ackley(**kwargs):
    x = np.fromiter(kwargs.values(), dtype=float)
    arg1 = -0.2 * np.sqrt(0.5 * (x[0] ** 2 + x[1] ** 2))
    arg2 = 0.5 * (np.cos(2. * np.pi * x[0]) + np.cos(2. * np.pi * x[1]))
    return -1.0 * (-20. * np.exp(arg1) - np.exp(arg2) + 20. + np.e)

# A. init logger, transformer and optimizer
orig_logger = JSONLogger(path="./orig_optimizer.json", reset=True)
orig_bounds_transformer = SequentialDomainReductionTransformer()
orig_optimizer = BayesianOptimization(
    f=ackley,
    pbounds=pbounds,
    verbose=0,
    random_state=1,
    bounds_transformer=orig_bounds_transformer
)
orig_optimizer.subscribe(Events.OPTIMIZATION_STEP, orig_logger)
orig_optimizer.maximize(init_points=2, n_iter=20)


# B. create new optimizer, transformer and load logs there
loaded_bounds_transformer = SequentialDomainReductionTransformer()
loaded_optimizer = BayesianOptimization(
    f=ackley,
    pbounds=pbounds,
    verbose=0,
    random_state=1,
    bounds_transformer=loaded_bounds_transformer
)
load_logs(loaded_optimizer, logs="./orig_optimizer.json")


# C. Let's continue optimization and compare the results. loaded_transformer become unresponsive or broken
loaded_optimizer.maximize(init_points=0, n_iter=20)
orig_optimizer.maximize(init_points=0, n_iter=20)

plt.plot(orig_optimizer.space.target, label='Original Optimizer')
plt.plot(loaded_optimizer.space.target, label='Loaded Optimizer')
plt.legend()

# D. We may compare transformers and see that loaded_one remains unchanged
````

**Expected behavior**
After loading the logs loaded_bounds_transformer should continue updating its bounds and loaded_optimizer should find an optimal points in the already defined boundaries instead of starting whole flow from the beginning.

**Screenshots**
![image](https://github.com/bayesian-optimization/BayesianOptimization/assets/15153503/4da43b5a-edcb-4aab-84a7-ecfa3df743f7)

**Environment (please complete the following information):**
 - OS: Windows 11
 - `python` Version 3.12.3
 - `numpy` 1.26.4
 - `scipy` 1.13.0
 - `bayesian-optimization` 1.5.0

**Comment by till-m** [comment] 2024-06-26 07:01
Hi @pawlissimo,

thanks for opening the issue and providing some code!
It doesn't look like you're loading anything for the bounds transformer, but in the original post you mentioned some sort of pickle/unpickle operation.

**Comment by pawlissimo** [comment] 2024-06-26 07:41
Hi @till-m,
Here I just provided basic code and expected outcome without my workarounds.
I may extend it with them if needed.

I think, that underlying issue seems to be related to losing ability to dump/restore Transformer's data and then linking it again with loaded optimizer after `load_logs()` command

**Comment by till-m** [comment] 2024-06-26 08:12
There's two things that you need to do:

1) Somehow restore the state of the bounds transformer, as it has some parameters (e.g. via pickle, as done below)
2) Restore the bounds, which have already been shrunk (also e.g. via pickle)

There are still some slight differences in the plots, which I assume come due to randomness.

```python
## core idea described here: https://bayesian-optimization.github.io/BayesianOptimization/domain_reduction.html
import numpy as np
from bayes_opt import BayesianOptimization
from bayes_opt import SequentialDomainReductionTransformer
from bayes_opt.logger import JSONLogger
from bayes_opt.event import Events
from bayes_opt.util import load_logs
import matplotlib.pyplot as plt

import pickle

pbounds = {'x': (-5, 5), 'y': (-5, 5)}
def ackley(**kwargs):
    x = np.fromiter(kwargs.values(), dtype=float)
    arg1 = -0.2 * np.sqrt(0.5 * (x[0] ** 2 + x[1] ** 2))
    arg2 = 0.5 * (np.cos(2. * np.pi * x[0]) + np.cos(2. * np.pi * x[1]))
    return -1.0 * (-20. * np.exp(arg1) - np.exp(arg2) + 20. + np.e)

# A. init logger, transformer and optimizer
orig_logger = JSONLogger(path="./orig_optimizer.json", reset=True)
orig_bounds_transformer = SequentialDomainReductionTransformer()
orig_optimizer = BayesianOptimization(
    f=ackley,
    pbounds=pbounds,
    verbose=0,
    random_state=1,
    bounds_transformer=orig_bounds_transformer
)
orig_optimizer.subscribe(Events.OPTIMIZATION_STEP, orig_logger)
orig_optimizer.maximize(init_points=2, n_iter=20)
with open('orig_transformer.pkl', 'wb') as f:
    pickle.dump((orig_bounds_transformer, orig_optimizer.space.array_to_params(orig_optimizer.space.bounds)), f)

with open('orig_transformer.pkl', 'rb') as f:
    loaded_bounds_transformer, loaded_bounds = pickle.load(f)

# B. create new optimizer, transformer and load logs there
loaded_optimizer = BayesianOptimization(
    f=ackley,
    pbounds=pbounds,
    verbose=0,
    random_state=1,
    bounds_transformer=SequentialDomainReductionTransformer()
)

load_logs(loaded_optimizer, logs="./orig_optimizer.json")
loaded_optimizer._bounds_transformer = loaded_bounds_transformer
loaded_optimizer.set_bounds(loaded_bounds)

# C. Let's continue optimization and compare the results. loaded_transformer become unresponsive or broken
loaded_optimizer.maximize(init_points=0, n_iter=20)
orig_optimizer.maximize(init_points=0, n_iter=20)

plt.plot(orig_optimizer.space.target, label='Original Optimizer')
plt.plot(loaded_optimizer.space.target, label='Loaded Optimizer')
plt.legend()

# D. We may compare transformers and see that loaded_one remains unchanged
```
![image](https://github.com/bayesian-optimization/BayesianOptimization/assets/36440677/bf5beaed-dc6b-425a-848a-07c51b49ec18)

@bwheelz36 Nonetheless, I think we should work towards proper serialization, there's really only so far one can push `JSON` logging (see also e.g. #478).

@pawlissimo let me know if this helps :)

**Comment by pawlissimo** [comment] 2024-06-26 09:13
Hi @till-m ,
Thanks a lot for your suggestion. It really looks more promising now. 

I see a few things here:
1. I fixed randomness as `random_state=1` and checked in BO code base to be sure, that GP and utility function produce exactly the same predictable results. So, for now I don't think differences related to some randomness
2. Loading bounds to the already loaded optimizer like `loaded_optimizer.set_bounds(loaded_bounds)` seems a bit strange and not so obvious to me, since we already loaded logs. BTW, it seems strange why we do not call `set_bounds` during `load_logs` automatically?
3. My general understanding is that during `load_logs()` in addition to ` optimizer.register(...)` we also need to update bounds for its transformer (if it exists).

**Comment by till-m** [comment] 2024-06-26 11:46
Hi @pawlissimo,

first of all, or 0.) Please consider that this loading from logs is a rather old functionality. Back when the optimization had fewer bells and whistles (e.g. no Domain Transformer, Constraints) it worked quite well. It hasn't really kept step with these additions, because most users don't _really_ care about serialization. For constraints, I've tried to make it work, but it was also a suprisingly delicate process. 
I do think we should have a better way of serializing the optimizer object (PRs are welcome, by the way :wink:). When in doubt, I would recommend pickling, though I am aware it's inelegant and I understand why you'd rather not use it in this. Nonetheless, if you're wondering why some things behave weirdly, the reason is that the optimization object has become to complicated and stateful for such a simple state restoration method. There is a lot of value in having human-readable logs, but they're also very restrictive!

## 1.)
yes, you did fix the `random_state`! The problem is, that the `random_state` mutates as it is used. In a sense, it is really only consistent if you call the exact same code. This is necessary, as otherwise the state could only really return one random number. Since the random state is used during the initial maximization, it is modified for the original optimizer. However, when loading the logs, the random_state is not used and remains unchanged.

consider the following code:
```python 
from bayes_opt.util import ensure_rng

state1 = ensure_rng(42)
state2 = ensure_rng(42)

print(state1.rand()) # something like this happens during the suggest step
print(state1.rand()) # the mutated state is called again and returns a different value
print(state2.rand()) # this is the loaded optimizer state, which was not mutated and returns the initial value
```

The random state exists to ensure that the same code executed twice can be made reproducible, not to align loaded optimizers, so I think this behaviour is fine. If you want the latter, you could manually reset/align all the states, which is however a bit messy:

```python
## core idea described here: https://bayesian-optimization.github.io/BayesianOptimization/domain_reduction.html
import numpy as np
from bayes_opt import BayesianOptimization
from bayes_opt import SequentialDomainReductionTransformer
from bayes_opt.logger import JSONLogger
from bayes_opt.event import Events
from bayes_opt.util import load_logs, ensure_rng
import matplotlib.pyplot as plt

import pickle

pbounds = {'x': (-5, 5), 'y': (-5, 5)}
def ackley(**kwargs):
    x = np.fromiter(kwargs.values(), dtype=float)
    arg1 = -0.2 * np.sqrt(0.5 * (x[0] ** 2 + x[1] ** 2))
    arg2 = 0.5 * (np.cos(2. * np.pi * x[0]) + np.cos(2. * np.pi * x[1]))
    return -1.0 * (-20. * np.exp(arg1) - np.exp(arg2) + 20. + np.e)

# A. init logger, transformer and optimizer
orig_logger = JSONLogger(path="./orig_optimizer.json", reset=True)
orig_bounds_transformer = SequentialDomainReductionTransformer()
orig_optimizer = BayesianOptimization(
    f=ackley,
    pbounds=pbounds,
    verbose=0,
    random_state=1,
    bounds_transformer=orig_bounds_transformer
)
orig_optimizer.subscribe(Events.OPTIMIZATION_STEP, orig_logger)
orig_optimizer.maximize(init_points=2, n_iter=20)
with open('orig_transformer.pkl', 'wb') as f:
    pickle.dump((orig_bounds_transformer, orig_optimizer.space.array_to_params(orig_optimizer.space.bounds)), f)

with open('orig_transformer.pkl', 'rb') as f:
    loaded_bounds_transformer, loaded_bounds = pickle.load(f)

# B. create new optimizer, transformer and load logs there
loaded_optimizer = BayesianOptimization(
    f=ackley,
    pbounds=pbounds,
    verbose=0,
    random_state=1,
    bounds_transformer=SequentialDomainReductionTransformer()
)

load_logs(loaded_optimizer, logs="./orig_optimizer.json")
loaded_optimizer._bounds_transformer = loaded_bounds_transformer
loaded_optimizer.set_bounds(loaded_bounds)

# Align random states
orig_optimizer._random_state = ensure_rng(42)
loaded_optimizer._random_state = ensure_rng(42)
orig_optimizer._gp.set_params(random_state=ensure_rng(42))
loaded_optimizer._gp.set_params(random_state=ensure_rng(42))
orig_optimizer._space.random_state = ensure_rng(42)
loaded_optimizer._space.random_state = ensure_rng(42)


# C. Let's continue optimization and compare the results. loaded_transformer become unresponsive or broken
loaded_optimizer.maximize(init_points=0, n_iter=20)
orig_optimizer.maximize(init_points=0, n_iter=20)

plt.plot(orig_optimizer.space.target, label='Original Optimizer')
plt.plot(loaded_optimizer.space.target, label='Loaded Optimizer')
plt.legend()

# D. We may compare transformers and see that loaded_one remains unchanged
```

As you can see, this does give you a consistent behaviour:

![image](https://github.com/bayesian-optimization/BayesianOptimization/assets/36440677/78f117a6-7096-404f-9514-0a228145d897)

## 2.)

The bounds are mutate during `maximize` by the bounds transformer (that's in some sense entirely what the bounds transformer is supposed to). However, these mutated bounds are not stored in the logs (see point 0 as for why). This is also the reason why we can't call `set_bounds`.

## 3.)
I'm not sure I understand what you're saying -- this is exactly the reason for point 2?


I hope this helps, don't hesitate to let me know if there are further questions.

Cheers,
Till

**Comment by till-m** [comment] 2024-06-30 09:49
Hey @pawlissimo,

glad to hear you found a solution!
I'm honestly not entirely sure what's happening with the random state of the GP. As far as I can tell, the 4 lines you added should not do anything. Yet, I observe the same behaviour. For what it's worth, I'm pretty confident that this has nothing to do with this library and is more likely to be a problem of either sklearn or numpy.

Sorry I couldn't be of more help.

**Comment by pawlissimo** [comment] 2024-07-01 06:41
Hi @till-m ,
Yes, you're right - there something strange inside GP that I couldn't understand after deeper analysis even. BTW was surprisingly difficult to find such workaround either.

But another core issue that my approach fixes is ability to continue optimization after some checkpoint. This is crucial in case of time/resource-consuming black-box functions and probably, this is only the option.

**Comment by till-m** [comment] 2024-07-01 08:40
Glad to hear!

I will close this issue. Let us know if you need any other help. :)

**Closed by till-m** 2024-07-01 08:40 UTC
Labels: bug, enhancement
